# Generated by Django 5.2.8 on 2025-11-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('threat_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('incident_type', models.CharField(choices=[('protest', 'Protest/Riot'), ('violence', 'Violence'), ('accident', 'Accident'), ('natural_disaster', 'Natural Disaster'), ('other', 'Other')], max_length=20)),
                ('sources', models.JSONField(default=list)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CCTVAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.CharField(max_length=500)),
                ('frame_image', models.ImageField(upload_to='cctv_frames/')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('crowd_density', models.FloatField(blank=True, null=True)),
                ('anomaly_detected', models.BooleanField(default=False)),
                ('detected_objects', models.JSONField(default=dict)),
                ('threat_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('incident_type', models.CharField(choices=[('protest', 'Protest/Riot'), ('violence', 'Violence'), ('accident', 'Accident'), ('natural_disaster', 'Natural Disaster'), ('other', 'Other')], max_length=20)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='citizen_reports/')),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('threat_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('incident_type', models.CharField(choices=[('protest', 'Protest/Riot'), ('violence', 'Violence'), ('accident', 'Accident'), ('natural_disaster', 'Natural Disaster'), ('other', 'Other')], max_length=20)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
